name: builder-cataloque
dependencies:
  - python=3.8.13
  - pytest=7.1.1
  - black=22.3.0
  - pip=22.1.2
  - pip:
      - pre_commit==2.18.1
      - -r requirements.txt
channels:
  - defaults
  - conda-forge
